language: python
python:
- 3.7-dev
script: pytest
before_deploy:
- openssl aes-256-cbc -K $encrypted_e5ce453b448a_key -iv $encrypted_e5ce453b448a_iv
  -in files-for-deployon-gae.tar.enc -out files-for-deployon-gae.tar
  -d
- tar xvf files-for-deployon-gae.tar
deploy:
  provider: gae
  keyfile: conteudo-negro-tech-c463a08bcb68.json
  project: conteudo-negro-tech

