version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db