version: '3'

services:
  db:
    image: postgres
    container_name: conteudo-tech-negro-postgres
    environment:
      POSTGRES_DB: conteudonegro
  web:
    container_name: conteudo-tech-negro
    build: .
    command: gunicorn --log-level DEBUG -t 60 --bind=0.0.0.0:5000 conteudo_tech_negro:app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db