FROM ruby:2

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler:1.17.2
RUN bundle install

COPY . .

CMD ["./your-daemon-or-script.rb"]
