"""empty message
Revision ID: 24ba56511889
Revises:
Create Date: 2018-11-18 15:28:56.031431
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ba56511889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('redes_sociais', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('conteudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('resumo', sa.String(length=250), nullable=False),
    sa.Column('data_adicao', sa.Date(), nullable=True),
    sa.Column('autora_id', sa.Integer(), nullable=True),
    sa.Column('tema', sa.String(length=250), nullable=True),
    sa.Column('tipo_conteudo', sa.String(length=250), nullable=True),
    sa.Column('imagem', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['autora_id'], ['autora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conteudo')
    op.drop_table('user')
    op.drop_table('autora')
    # ### end Alembic commands ###